name: Version Bump

on:
    push:
        branches:
            - main
        paths-ignore: sfdx-project.json

env:
    SFDX_DISABLE_DNS_CHECK: true

jobs:
    validate:
        name: Bump Version
        runs-on: 'ubuntu-latest'

        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ vars.NODE_VERSION }}
                  cache: npm

            - name: Install dependencies
              run: npm install

            - name: Bump Version(s) and Push
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GH_USERNAME: ${{ github.actor }}
                  GH_USERID: ${GITHUB_ACTOR_ID}
                  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
              run: |
                  git remote set-url --push origin https://$GH_USERNAME:$GH_TOKEN@github.com/packocz/PackageVersions
                  git checkout $BRANCH_NAME
                  git config --global user.email "$GH_USERID+GH_USERNAME@users.noreply.github.com"
                  git config --global user.name "$GH_USERNAME"
                  node ./scripts/node/bumpVersion.js
                  if [[ ! -z "$(git status --porcelain)" ]]; then git add sfdx-project.json && git commit --no-verify --amend --no-edit && git push origin $BRANCH_NAME --force; fi
