name: Release

on:
    workflow_dispatch:
        inputs:
            commit:
                description: Commit, branch or tag to create build from
                default: main
                required: true
            release-name:
                description: Custom name for the release, e.g. APP-v1.0 from "APP-v1.0.1"
                required: true
            release-number:
                description: Incremental number for the release, e.g last 1 from  from "APP-v1.0.1"
                required: true

env:
    SFDX_DISABLE_DNS_CHECK: true
    COMMIT_ID: ${{ inputs.commit }}
    RELEASE_NAME: ${{ inputs.release-name }}
    RELEASE_TAG: '${{ inputs.release-name }}.${{ inputs.release-number }}'

jobs:
    create-release:
        name: Create Release
        runs-on: 'ubuntu-latest'

        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Auth Git
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GH_USERNAME: ${{ github.actor }}
              run: |
                  git remote set-url origin https://$GH_USERNAME:$GH_TOKEN@github.com/packocz/PackageVersions

            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ vars.NODE_VERSION }}
                  cache: npm

            - name: Install dependencies
              run: |
                  npm i -g @salesforce/cli @dxatscale/sfpowerscripts${{ vars.SFP_VERSION }}
                  npm install

            - name: 'Populate auth file with DevHub secret'
              shell: bash
              run: |
                  echo ${{ secrets.DEVHUB_SFDX_AUTH_URL}} > ./DEVHUB_KEY.txt
                  secretFileSize=$(wc -c "./DEVHUB_KEY.txt" | awk '{print $1}')
                  if [ $secretFileSize == 1 ]; then
                      echo "Missing DEVHUB_KEY secret.";
                      exit 1;
                  fi

            - name: 'Authenticate DevHub'
              run: sfdx auth:sfdxurl:store -f ./DEVHUB_KEY.txt -a devhub

            - name: Create packages
              run: |
                  sfp orchestrator:quickbuild -v devhub --branch ${COMMIT_ID} --buildnumber ${GITHUB_RUN_ID} --tag=${RELEASE_TAG}
                  sfp orchestrator:publish --artifactdir artifacts --gittag --pushgittag -f scripts/bash/publishSkip.sh

            # sfp orchestrator:promote -v devhub
            - name: Generate and push Release Definition
              run: |
                  sfp releasedefinition:generate --branchname "${COMMIT_ID}" --gitref "${COMMIT_ID}" --directory "release-definitions/${RELEASE_NAME}" --configfile config/release-definition.yml --releasename "${RELEASE_TAG}"
                  git fetch origin "${COMMIT_ID}"
                  git checkout "${COMMIT_ID}"

            - name: Tag Release
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GH_USERNAME: ${{ github.actor }}
              run: |
                  git tag "${RELEASE_TAG}" "${COMMIT_ID}"
                  git push origin "${RELEASE_TAG}"
                  git checkout -b "release/${RELEASE_NAME}"
                  git push origin "release/${RELEASE_NAME}"

            - name: Generate Change Log
              run: |
                  sfp changelog:generate --branchname=origin/changelog --releasename=${RELEASE_TAG} --workitemfilter=${TICKET_REGEX} --directory=release-definitions --workitemurl=${WORKITEM_URL} --showallartifacts >> changelog.md

            - name: Generate Change Log
              run: |
                  sed -n "/Generating changelog.../,/Committed File/p" changelog.md > temp.txt && mv temp.txt changelog.md
                  sed '1d;$d' changelog.md > temp.txt && mv temp.txt changelog.md

            - name: Create Release on GitHub
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  node ./scripts/node/createRelease.js "${RELEASE_TAG}" "changelog.md"

            - name: Bump Version on main and Push
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GH_USERNAME: ${{ github.actor }}
                  GH_USERID: ${GITHUB_ACTOR_ID}
              run: |
                  git checkout "${COMMIT_ID}"
                  node ./scripts/node/bumpVersion.js "minor" "all"
                  git add sfdx-project.json
                  git commit -m "Bump Package Version(s) post release"
                  git push origin "${COMMIT_ID}"
